In [11]:
import pandas as pd

In [17]:
import requests
from io import StringIO

In [18]:
url="https://raw.githubusercontent.com/WuCandice/Superstore-Sales-Analysis/refs/heads/main/dataset/Superstore%20Dataset.csv"

In [19]:
data = requests.get(url)

In [21]:
data_text= StringIO(data.text)
df = pd.read_csv(data_text)
df.head(1)

         Order ID  Order Date   Ship Date  ... Quantity Discount  Profit
0  CA-2019-103800  2019-01-03  2019-01-07  ...        2      0.2  5.5512

[1 rows x 20 columns]

In [22]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [24]:
new_df = df[["Ship Mode", "Country","Region","Category","Discount","Profit"]]
new_df.head(2)

        Ship Mode        Country   Region         Category  Discount  Profit
0  Standard Class  United States  Central  Office Supplies       0.2  5.5512
1  Standard Class  United States  Central  Office Supplies       0.2  4.2717

In [34]:
df1 = new_df.copy()
df2= new_df.copy()
df3= new_df.copy()
df4= new_df.copy()
df5= new_df.copy()

In [30]:
new_df["Category"].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [31]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [32]:
# label encoder

In [33]:
le = LabelEncoder()

In [35]:
df1["Category"]= le.fit_transform(df1["Category"])

In [37]:
df1.head(2)

        Ship Mode        Country   Region  Category  Discount  Profit
0  Standard Class  United States  Central         1       0.2  5.5512
1  Standard Class  United States  Central         1       0.2  4.2717

In [38]:
# ordinal encoder
ord = OrdinalEncoder()

In [40]:
df1["Country"]= ord.fit_transform(df1[["Country"]])

In [41]:
df1.head(2)

        Ship Mode  Country   Region  Category  Discount  Profit
0  Standard Class      0.0  Central         1       0.2  5.5512
1  Standard Class      0.0  Central         1       0.2  4.2717

In [43]:
# one hot encoding
ohe= OneHotEncoder(sparse_output=False)

In [45]:
encode= ohe.fit_transform(df1[["Region"]])

In [46]:
encode

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [49]:
df1_new= pd.DataFrame(encode, columns=ohe.get_feature_names_out(["Region"]))

In [50]:
df1_new.head()

   Region_Central  Region_East  Region_South  Region_West
0             1.0          0.0           0.0          0.0
1             1.0          0.0           0.0          0.0
2             1.0          0.0           0.0          0.0
3             1.0          0.0           0.0          0.0
4             0.0          1.0           0.0          0.0

In [51]:
df1.head(1)

        Ship Mode  Country   Region  Category  Discount  Profit
0  Standard Class      0.0  Central         1       0.2  5.5512

In [52]:
df1= df1.drop(["Region"],axis=1)

In [53]:
df1.head(1)

        Ship Mode  Country  Category  Discount  Profit
0  Standard Class      0.0         1       0.2  5.5512

In [57]:
df1_update= pd.concat([df1_new,df1], axis=1)

In [59]:
df1_update

      Region_Central  Region_East  Region_South  ...  Category Discount   Profit
0                1.0          0.0           0.0  ...         1      0.2   5.5512
1                1.0          0.0           0.0  ...         1      0.2   4.2717
2                1.0          0.0           0.0  ...         1      0.2 -64.7748
3                1.0          0.0           0.0  ...         1      0.8  -5.4870
4                0.0          1.0           0.0  ...         1      0.2   4.8840
...              ...          ...           ...  ...       ...      ...      ...
9989             0.0          0.0           0.0  ...         1      0.2  -0.6048
9990             0.0          1.0           0.0  ...         1      0.2  19.7910
9991             0.0          1.0           0.0  ...         2      0.0   2.7279
9992             0.0          0.0           0.0  ...         1      0.2   4.5188
9993             0.0          1.0           0.0  ...         0      0.2  12.1176

[9994 rows x 9 columns]

In [60]:
# 
df1_update.head(1)

   Region_Central  Region_East  Region_South  ...  Category Discount  Profit
0             1.0          0.0           0.0  ...         1      0.2  5.5512

[1 rows x 9 columns]

In [62]:
df1_update["Ship Mode"].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [68]:
# create dummay variable 
dummy= pd.get_dummies(df1_update["Ship Mode"], drop_first=True).astype("int64")
dummy

      Same Day  Second Class  Standard Class
0            0             0               1
1            0             0               1
2            0             0               1
3            0             0               1
4            0             0               1
...        ...           ...             ...
9989         0             0               1
9990         0             0               1
9991         0             0               1
9992         0             0               1
9993         0             0               1

[9994 rows x 3 columns]

In [69]:
df1_update= df1_update.drop(["Ship Mode"], axis=1)
df1_update.head(1)

   Region_Central  Region_East  Region_South  ...  Category  Discount  Profit
0             1.0          0.0           0.0  ...         1       0.2  5.5512

[1 rows x 8 columns]

In [70]:
df1= pd.concat([df1_update, dummy], axis=1)
df1.head(1)

   Region_Central  Region_East  ...  Second Class  Standard Class
0             1.0          0.0  ...             0               1

[1 rows x 11 columns]

In [71]:
# replace 
df2.head(2)

        Ship Mode        Country   Region         Category  Discount  Profit
0  Standard Class  United States  Central  Office Supplies       0.2  5.5512
1  Standard Class  United States  Central  Office Supplies       0.2  4.2717

In [72]:
df2["Ship Mode"].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [ ]:
df2["Ship Mode"]= df2["Ship Mode"].replace(["Standard Class","Second Class","First Class","Same Day"],[4,2,1,3])

C:\Users\Faculty\AppData\Local\Temp\ipykernel_9480\300471458.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2["Ship Mode"]= df2["Ship Mode"].replace(["Standard Class","Second Class","First Class","Same Day"],[4,2,1,3])

In [74]:

df2.head(2)

   Ship Mode        Country   Region         Category  Discount  Profit
0          4  United States  Central  Office Supplies       0.2  5.5512
1          4  United States  Central  Office Supplies       0.2  4.2717

In [76]:
df2["Region"].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [78]:
df2["Region"]= df2["Region"].replace({"West":3,"East":1,"South":2,"Central":4})
df2.head(2)

C:\Users\Faculty\AppData\Local\Temp\ipykernel_9480\3300502424.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2["Region"]= df2["Region"].replace({"West":3,"East":1,"South":2,"Central":4})

   Ship Mode        Country  Region         Category  Discount  Profit
0          4  United States       4  Office Supplies       0.2  5.5512
1          4  United States       4  Office Supplies       0.2  4.2717

In [79]:
df2["Region"].value_counts()

Region
3    3203
1    2848
4    2323
2    1620
Name: count, dtype: int64

In [80]:
# using loop
from pandas.api.types import is_numeric_dtype

In [81]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Ship Mode  9994 non-null   int64
 1   Country    9994 non-null   object
 2   Region     9994 non-null   int64
 3   Category   9994 non-null   object
 4   Discount   9994 non-null   float64
 5   Profit     9994 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 468.6+ KB

In [82]:
df2.columns

Index(['Ship Mode', 'Country', 'Region', 'Category', 'Discount', 'Profit'], dtype='object')

In [84]:
for col in df2.columns:
     if is_numeric_dtype(df2[col]):
          continue
     else:
          df2[col]= le.fit_transform(df2[col])

In [85]:
df2.head(2)

   Ship Mode  Country  Region  Category  Discount  Profit
0          4        0       4         1       0.2  5.5512
1          4        0       4         1       0.2  4.2717

In [86]:
df3.head()

        Ship Mode        Country   Region         Category  Discount   Profit
0  Standard Class  United States  Central  Office Supplies       0.2   5.5512
1  Standard Class  United States  Central  Office Supplies       0.2   4.2717
2  Standard Class  United States  Central  Office Supplies       0.2 -64.7748
3  Standard Class  United States  Central  Office Supplies       0.8  -5.4870
4  Standard Class  United States     East  Office Supplies       0.2   4.8840

In [87]:
# ordinal encong using for loop

In [88]:
# one hot encoding

In [90]:
for col in df3.columns:
     if is_numeric_dtype(df3[col]):
          continue
     else:
          dummy= pd.get_dummies(df3[col], drop_first=True).astype("int64")
          df3.drop([col], axis=1, inplace=True)
          df3=pd.concat([df3, dummy], axis=1)

In [91]:
df3.head()

   Discount   Profit  Same Day  ...  West  Office Supplies  Technology
0       0.2   5.5512         0  ...     0                1           0
1       0.2   4.2717         0  ...     0                1           0
2       0.2 -64.7748         0  ...     0                1           0
3       0.8  -5.4870         0  ...     0                1           0
4       0.2   4.8840         0  ...     0                1           0

[5 rows x 10 columns]

In [92]:
# replace for loop
df4.head(1)

        Ship Mode        Country   Region         Category  Discount  Profit
0  Standard Class  United States  Central  Office Supplies       0.2  5.5512

In [93]:
df4["Ship Mode"].nunique()

4

In [ ]:
['Standard Class', 'First Class', 'Second Class', 'Same Day'][]

In [ ]:
df4["Ship Mode"].unique()

array(['Standard Class', 'First Class', 'Second Class', 'Same Day'],
      dtype=object)

In [96]:
li= df4["Ship Mode"].unique().tolist()

In [97]:
li

['Standard Class', 'First Class', 'Second Class', 'Same Day']

In [98]:
for col in df4.columns:
     if is_numeric_dtype(df4[col]):
          continue
     else:
          uni= df4[col].nunique()
          li= df4[col].unique().tolist()
          if uni==1:
               df4[col]= df4[col].replace(li,[1])
          elif uni==2:
               df4[col]= df4[col].replace(li,[0,1])
          elif uni==3:
               df4[col]= df4[col].replace(li,[0,1,3])
          elif uni==4:
               df4[col]= df4[col].replace(li,[0,1,3,4])

C:\Users\Faculty\AppData\Local\Temp\ipykernel_9480\3454063844.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4[col]= df4[col].replace(li,[0,1,3,4])
C:\Users\Faculty\AppData\Local\Temp\ipykernel_9480\3454063844.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4[col]= df4[col].replace(li,[1])
C:\Users\Faculty\AppData\Local\Temp\ipykernel_9480\3454063844.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4[col]= df4[col].replace(li,[0,1,3])

In [100]:
df4.head(2)

   Ship Mode  Country  Region  Category  Discount  Profit
0          0        1       0         0       0.2  5.5512
1          0        1       0         0       0.2  4.2717